version: '3.9'

#Services for composing up Database and API together
services:

  #DATABASE SERVICE
  mongoDB:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongoDB:/data/db

  #API SERVICE
  api:
    build: .
    ports: 
      - 5001:5000
    environment:
      PORT: 5000
      MONGO_URI: PUT_YOUT_MONGO_DB_URI_HERE
    depends_on:
      - mongoDB

volumes:
  mongoDB: {}