version: '3.9'

#Services for composing up Database and API together
services:

  #DATABASE SERVICE
  mongoDB:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongoDB:/data/db

  #API SERVICE
  api:
    build: .
    ports: 
      - 5001:5000
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://akash:sky12345@cluster0.lrltv0q.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongoDB

volumes:
  mongoDB: {}